config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :subscriptions
  root to: 'application#index'

  resources :categories, only: %i[index new create]
  get '/categories/:name', to: 'posts#index', as: 'category'

  resources :comments, only: %i[create update destroy]
  resources :posts do
    resources :comments, only: [:edit]
  end
  resources :users

  # Sessions
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Colloborator
  resources :collaborators, only: [:destroy]
  post '/collaborator', to: 'collaborators#create'

  get '/analytics', to: 'analytics#home', as: 'analytics'
  # delete '/collaborator/:id', to: 'collaborators#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :comments, dependent: :destroy
  has_many :posts, through: :comments
  has_many :posts, dependent: :destroy
  has_many :collaborators, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :categories, through: :subscriptions

  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  def self.most_comments
    all.max do |a, b|
      a.comments.count <=> b.comments.count
    end
  end

  def self.least_comments
    all.min do |a, b|
      a.comments.count <=> b.comments.count
    end
  end

  def self.most_collaborators
    all.max do |a, b|
      a.collaborators.count <=> b.collaborators.count
    end
  end

  def self.least_collaborators
    all.min do |a, b|
      a.collaborators.count <=> b.collaborators.count
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :find_user, only: %w[show edit update destroy]
  before_action :require_login_user, only: %w[edit update destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session['user_id'] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session.clear
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_card.erb
<div class="ui fluid card">
  <div class="image">
    <img src="https://semantic-ui.com/images/avatar2/large/kristy.png">
  </div>
  <div class="content">
    <a class="header"><%= @user.name.capitalize %></a>
    <div class="meta">
      <span class="date">Joined on <%= @user.created_at.strftime("%b %d, %Y") %></span>
    </div>
    <div class="description"><%= @user.name.capitalize %> is an art director living in New York.</div>
  </div>
  <div class="extra content">
    <a>
    <i class="user icon"></i>
      22 Friends
    </a>
  </div>
</div>

<% if @user.id == session["user_id"] %>
  <p><%= link_to edit_user_path(@user), class: "ui fluid primary button" do %>
    <i class="edit icon"></i> Edit Profile
  <% end %></p>
  <p><%= link_to @user, method: "delete", :data => {:confirm => 'Do you really want to delete your profile?'}, class: "ui fluid red button" do %>
    <i class="exclamation triangle icon"></i> Delete Profile
  <% end %></p>

<% else %>
  <p><%= link_to "mailto:#{@user.email}", target: :_blank, class: "ui fluid positive button" do %>
    <i class="envelope icon"></i> Email <%= @user.name.capitalize %>
  <% end %></p>
<% end %>

app/views/users/_user_form.erb
<%= form_for User.new, html: {class:"ui form"}  do |f| %>
  <div class="field">
    <%= f.label :name, "Choose a Username" %>
    <%= f.text_field :name, placeholder: "Username" %>
  </div>
  <div class="field">
    <%= f.label :email, "Enter Your Email" %>
    <%= f.email_field :email, placeholder: "Email" %>
  </div>
  <div class="field">
    <%= f.label :password, "Create a Password" %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Comfirm Your Password" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.submit "Submit", :class => "ui button" %>
  </div>
<% end %>

app/views/users/edit.erb
<div class="row">
	<div class="eleven wide column">

    <h1 class="ui header">Edit Profile</h1>

    <%= render partial: 'shared/error_list', locals: {object: @user }%>
    <%= render 'user_form'%>
  
  </div>

  <div class="five wide column">
    <%= render "user_card" %>
  </div>

</div>

app/views/users/index.erb
<div class="row">
	<div class="eleven wide column">

        <h1 class="ui header">Users</h1>

        <% @users.each do |user| %>
            <h2><%= user.name %> (<%= link_to "View Profile", user_path(user)%>) | Total Posts: <%= user.posts.length %> | Total Comments: <%= user.comments.length %> </h2>
        <% end %>
    </div>

    <div class="five wide column">
    </div>

</div>

app/views/users/new.erb
<div class="row">
	<div class="eleven wide column">

    <h1>Create new User</h1>
    <%= render partial: 'shared/error_list', locals: {object: @user }%>
    <%= render 'user_form'%>

    <p><%= link_to 'Cancel', users_path %></p>
    
  </div>
</div>

app/views/users/show.erb
<div class="row">
	<div class="eleven wide column">

        <h1 class="ui header"><%= @user.name.capitalize %>'s Profile Page</h1>

        <h2 class="ui dividing header"><%= @user.name.capitalize %>'s Posts:</h2>
        <% if @user.posts.length > 0 %>
            <div class="ui relaxed list">
            <% @user.posts.each do |post| %>
                <div class="item ui comments" style="margin: 0!important;">
                    <div class="content comment">
                        <h3 class="header"><%= link_to post.title, post_path(post)%></h3>
                        <div class="metadata" style="margin-left: 0;">
                            <span class="date">Posted <%= time_ago_in_words(post.created_at) %>
                        </div>
                    </div>
                </div>
            <% end %>
            </div>
        <% else %>
            <p><%= @user.name.capitalize %> hasn't started any projects.</p>
        <% end %>

        <h2 class="ui dividing header"><%= @user.name.capitalize %>'s Collaborations:</h2>
        <% if @user.collaborators.length > 0 %>
            <div class="ui relaxed list">
            <% @user.collaborators.each do |collaborator| %>
                <div class="item ui comments" style="margin: 0!important;">
                    <div class="content comment">
                        <h4 class="header"><%= link_to collaborator.post.title, post_path(collaborator.post)%></h4>
                    </div>
                </div>
            <% end %>
            </div>
        <% else %>
            <p><%= @user.name.capitalize %> isn't collaborating on any projects.</p>
        <% end %>

        <h3 class="ui dividing header">Latest Comments:</h3>
        <% if @user.comments.length > 0 %>
            <div class="ui comments">
            <% @user.comments.order('created_at DESC').limit(5).each do |comment| %>
                <div class="comment">
                     <div class="content">
                        <div class="text"><%= comment.content %></div>
                        <div class="metadata" style="margin-left: 0;">
                            <span class="date"><%= comment.created_at.strftime("%b %d, %Y") %></span> in <%= link_to comment.post.title, post_path(comment.post) %>
                        </div>
                    </div>
                </div>
            <% end %>
            </div>
        <% else %>
            <p><%= @user.name.capitalize %> hasn't left any comments.</p>
        <% end %>

    </div>

    <div class="five wide column">
        <%= render "user_card" %>
	</div>

</div>