config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :subscriptions
  root to: 'application#index'

  resources :categories, only: %i[index new create]
  get '/categories/:name', to: 'posts#index', as: 'category'

  resources :comments, only: %i[create update destroy]
  resources :posts do
    resources :comments, only: [:edit]
  end
  resources :users

  # Sessions
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Colloborator
  resources :collaborators, only: [:destroy]
  post '/collaborator', to: 'collaborators#create'

  get '/analytics', to: 'analytics#home', as: 'analytics'
  # delete '/collaborator/:id', to: 'collaborators#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_many :comments
  has_many :users, through: :comments
  belongs_to :category
  belongs_to :user
  belongs_to :tag
  has_many :collaborators

  validates :title, presence: true
  validates :content, presence: true
  validates :user_id, presence: true
  validates :tag_id, presence: true
  validates :category_id, presence: true

  def self.search(user, search)
    if user != '' && search == 'subscription'
      user = User.find(user)
      category_ids = user.categories.map(&:id)
      Post.where(category_id: category_ids)
    else
      all
    end
  end

  def self.most_comments
    all.max do |a, b|
      a.comments.count <=> b.comments.count
    end
  end

  def self.most_collaborators
    all.max do |a, b|
      a.collaborators.count <=> b.collaborators.count
    end
  end

  def self.most_recent_post
    order(:created_at).last
  end

  def self.longest_title
    order('length(title) desc').first
  end

  def self.longest_content
    order('length(content) desc').first
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :find_post, only: %w[show edit update destroy]
  before_action :require_login_post, only: %i[edit update destroy]
  before_action :require_login, only: %w[new create]

  def index
    # @posts = Post.order('created_at desc')
    @category = Category.find_by(name: params[:name])
    if @category
      @posts = Post.where(category: @category)
    else
      redirect_to '/'
    end
  end

  def show
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = User.find(session['user_id'])
    if @post.valid?
      @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :tag_id, :category_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post_form.erb
<%= form_for @post, html: {class:"ui form"} do |f| %>
  <div class="field">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, { prompt: "Select a Category" }, {class:"ui fluid search selection dropdown"} %>
  </div>
  <div class="field">
    <%= f.label :title, "Post Title" %>
    <%= f.text_field :title, placeholder: "" %>
  </div>
  <div class="field">
    <%= f.label :content, "Post Content" %>
    <%= f.text_area :content, placeholder: "" %>
  </div>
  <div class="field">
    <%= f.label :tag_id %>
    <%= f.collection_select :tag_id, Tag.all, :id, :name, { prompt: "Select a Tag" }, {class:"ui fluid search selection dropdown"} %>
  </div>  
  <div class="field">
    <%= f.submit "Submit", :class => "ui button" %>
  </div>
<% end %>

app/views/posts/edit.erb
<h1>Edit Post</h1>
<%= render partial: 'shared/error_list', locals: {object: @post}%>
<%= render "post_form"%>

app/views/posts/index.erb
<div class="row">
	<div class="eleven wide column">
		<% if @posts.any? %>
			<h1 class="ui header"><%= @posts.first.category.name.capitalize %> Posts</h1>
		<% else %>
			<h1>No Posts Found!</h1>
			<%= link_to new_post_path, class:"ui positive button" do %>
				<i class="pencil alternate icon"></i> Create First Post
			<% end %>
		<% end %>

		<ul class="posts-list">
			<% @posts.each do |post| %>
			<li>
				<div>
					<p>Posted by <%= link_to post.user.name.capitalize, user_path(post.user) %> 
					<%= time_ago_in_words(post.created_at) %> ago</p>
				</div>
				<h2><%= link_to post.title, post_path(post) %></h2>
				<p><%= post.comments.count %> Comments | Tags: <%= link_to post.tag.name.capitalize, "#" %></p>
			</li>
			<% end %>
		</ul>

		</div>

    <div class="five wide column">

		</div>

</div>

app/views/posts/new.erb
<div class="row">
	<div class="eleven wide column">

    <h1>Create New Post</h1>

    <%= render partial: 'shared/error_list', locals: { object: @post}%>
    <%= render "post_form"%>
  
  </div>

  <div class="five wide column">
	</div>

</div>

app/views/posts/show.erb
<div class="row">
	<div class="sixteen wide column">
	<p>
		<strong><%= link_to @post.category.name.capitalize, category_path(@post.category.name) %></strong> • 
		Posted by <%= link_to @post.user.name.capitalize, user_path(@post.user) %> <%= time_ago_in_words(@post.created_at) %> ago
	</p>
	</div>
</div>

<div class="row">
	<div class="eleven wide column">
		<div>
			<h1><%= @post.title%></h1>
			<p><%= @post.content%></p>
		</div>

		<div class="ui comments">
			<h3 class="ui dividing header">Comments</h3>
			<% @post.comments.each do |comment| %>
			<div class="comment">
				<a class="avatar">
					<img src=<%= asset_path('avatar.png') %>>
				</a>
				<div class="content">
					<a class="author"><strong><%= link_to comment.user.name.capitalize, user_path(comment.user) %></strong></a>
					<div class="metadata">
						<span class="date"><%= time_ago_in_words(comment.created_at).capitalize %> ago</span>
					</div>
					<div class="text">
						<%= comment.content%>
					</div>
					<% if comment.user_id == session["user_id"] %>
					<div class="actions">
						<%= link_to "Edit Comment", edit_post_comment_path(@post, comment) %>
						<%= link_to "Delete Comment", comment_path(comment), method: "Delete", data: { confirm: 'Really delete this comment?' }  %>
					</div>
					<% end %>
				</div>
			</div>  
			<% end %>
		</div>

		<% if flash[:notice] %>
				<div class="notice"><%= flash[:notice] %></div>
		<% end %>

		<%= form_tag "/comments", :class => 'ui form' do %>
			<div class="field">
				<%= label_tag :content, "Leave a Comment:" %>
				<%= text_field_tag :content %>
				<%= hidden_field_tag :post_id, @post.id %>
			</div>
			<div class="field">
				<%= submit_tag "Create Comment", :class => "ui button" %>
			</div>
		<% end %>

	</div>

	<div class="five wide column">
		<h3 class="ui dividing header">Collaborators</h3>
		<div class="ui bulleted list">
			<% @post.collaborators.each do |collaborator| %>
				<div class="item"><%= link_to collaborator.user.name.capitalize, user_path(collaborator.user) %>
				<% if collaborator.user == find_current_user%>
					<%= link_to collaborator_path(collaborator), method: "Delete", class: "", title: "Remove self from project" do %>
						<i class="delete icon"></i>
					<% end %>
				<% end %>
				</div>
			<% end %>
		</div>
		<% unless @post.user_id == session["user_id"]%>
			<%= form_tag "/collaborator", :class => 'ui form'  do %>
				<%= hidden_field_tag :user_id, session["user_id"]%>
				<%= hidden_field_tag :post_id, @post.id %>
				<div class="field">
					<%= submit_tag "Collaborate!", :class => "ui button" %>
				</div>
			<% end %>
		<% end %>

		<h3>More From <%= @post.category.name.capitalize %> </h3>
		<% @posts.where(category: @post.category).take(6).each do |post| %>
			<p><%= link_to post.title, post_path(post) %></p>
		<% end %>
	
	</div>

</div>