config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :subscriptions
  root to: 'application#index'

  resources :categories, only: %i[index new create]
  get '/categories/:name', to: 'posts#index', as: 'category'

  resources :comments, only: %i[create update destroy]
  resources :posts do
    resources :comments, only: [:edit]
  end
  resources :users

  # Sessions
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Colloborator
  resources :collaborators, only: [:destroy]
  post '/collaborator', to: 'collaborators#create'

  get '/analytics', to: 'analytics#home', as: 'analytics'
  # delete '/collaborator/:id', to: 'collaborators#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts
  has_many :subscriptions
  has_many :users, through: :subscriptions
  validates :name, uniqueness: true, presence: true

  def subscribers
    users
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
    @category = Category.new
  end

  def show
    @category = Category.find_by(name: params[:name])
  end

  def new
    @category = Category.new
  end

  def create
    downcase_name = params[:category][:name].downcase
    @category = Category.new(name: downcase_name)
    if @category.valid?
      @category.save
      redirect_to category_path(@category.name)
    else
      flash[:notice] = @category.errors.full_messages.join(' ')
      redirect_back(fallback_location: categories_path)
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category_form.erb
<%= form_for @category, html: {class:"ui form"} do |f| %>
  <div class="field">
    <%= f.label :name, "Create New Category" %>
    <%= f.text_field :name, placeholder: "Enter category name" %>
  </div>
  <div class="field">
    <%= f.submit "Submit", :class => "ui button" do %>
      <i class="pencil alternate icon"></i> Create Category
    <% end %>
  </div>
  
<% end %>

app/views/categories/index.html.erb
<div class="row">
	<div class="eleven wide column">

    <% @categories.each do |category| %>
    <div class="ui segment">
      <h2><%= link_to category.name.capitalize, category_path(category.name.downcase) %>
        <% if logged_in? %>
          <span class="inline-button">
          <% if category.subscribers.any?{|object| object.id == session[:user_id] } %>
            <%= link_to 'Unsubscribe', subscription_path(:id => Subscription.find_by(user_id: session[:user_id], category_id: category.id)), :method=> :delete, class: "ui fluid basic button" %>
          <% else %>
            <%= link_to 'Subscribe', subscriptions_path(:category_id => category.id, :user_id=> session[:user_id]), :method=> :post, class: "ui fluid button default" %>
          <% end %>
          </span>
        <% end %>
      </h2>
    </div>
    <% end %>

  </div>

  <div class="five wide column">
    <!-- <%= link_to "Back to Homepage", root_path %> -->
    <% if logged_in? %>
      <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
      <% end %>
      <!-- <%= link_to "Create new Category", new_category_path %> -->
      <%= render "category_form" %>
    <% end %>
	</div>

</div>

app/views/categories/new.html.erb
<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.submit%>
  </div>
<% end %>