config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :subscriptions
  root to: 'application#index'

  resources :categories, only: %i[index new create]
  get '/categories/:name', to: 'posts#index', as: 'category'

  resources :comments, only: %i[create update destroy]
  resources :posts do
    resources :comments, only: [:edit]
  end
  resources :users

  # Sessions
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Colloborator
  resources :collaborators, only: [:destroy]
  post '/collaborator', to: 'collaborators#create'

  get '/analytics', to: 'analytics#home', as: 'analytics'
  # delete '/collaborator/:id', to: 'collaborators#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :find_current_user, :logged_in?

  def index
    @posts = Post.search(params[:id], params[:search]).sort { |a, b| b.created_at <=> a.created_at }
  end

  def find_current_user
    @user = User.find(session['user_id']) if session['user_id']
  end

  def logged_in?
    session['user_id']
  end

  private

  # def authorized
  #   redirect_to login_path unless logged_in?
  # end

  def require_login
    redirect_to login_path unless session.include? 'user_id'
  end

  def require_login_post
    redirect_to login_path unless session['user_id'] == @post.user_id
  end

  def require_login_user
    redirect_to login_path unless session['user_id'] == @user.id
  end

  def require_login_comment
    redirect_to login_path unless session['user_id'] == @comment.user_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_login_modal.erb
<div class="ui modal login-modal" style="padding: 2em;">
  <i class="close icon"></i>
  <div class="ui two column very relaxed grid">
    <div class="column">
      <h2 class="ui header">Login</h2>
      <%= render "sessions/login_form" %>
    </div>
    <div class="column">
      <h2 class="ui header">Create Account</h2>
      <%= render "users/user_form"  %>
    </div>
  </div>
  <div class="ui vertical divider">
    or
  </div>
</div>

app/views/application/_navbar.html.erb
<nav class="ui stackable menu">
  <div class="ui container">
    <a href="<%= root_path %>" class="header item">
      <img class="logo" src=<%= asset_path('dog.png') %>> Kublai
    </a>
    <a href="<%= categories_path %>" class="item">
      <i class="grid layout icon"></i> Browse Categories
    </a>
    <a href="<%= users_path %>" class="item">
      <i class="users icon"></i> Browse Users
    </a>
    <a href="<%= analytics_path %>" class="item">
      <i class="clipboard list icon"></i> Site Analytics
    </a>
    <div class="right item">
      <% if find_current_user %>
        <%= link_to user_path(find_current_user), class: "ui fluid primary button" do %>
          <i class="user circle icon"></i> <%= find_current_user.name.capitalize %>
        <% end %>
        <%= link_to "Logout", logout_path, method: "delete", class: "ui red button" %>
      <% else %>
        <%= link_to "Login or Create Account", login_path, class: "login-create-button ui fluid primary button" %>
        <!-- <%= link_to "Create Account", new_user_path, class: "login-create-button ui fluid red button" %> -->
      <% end %>
      
    </div>
  </div>
</nav>

<%= render "login_modal" %>

app/views/application/index.html.erb
<div class="row">
	<% if logged_in? %>
		<div class="left floated left aligned eight wide column">
			<%= link_to new_post_path, class:"ui positive button" do %>
				<i class="pencil alternate icon"></i> Create New Post
			<% end %>
		</div>
		<div class="right floated right aligned eight wide column">
			<%= form_tag root_path, :method => 'get', html: {class:"ui form"}  do %>
				<div class="field">
					<%= hidden_field_tag :id, session[:user_id] %>
					<%= select_tag(:search, options_for_select([['Show All', 1], ['Show Subscriptions', "subscription"]]), {class:"ui search selection dropdown"}) %>
					<%= submit_tag "Filter Posts", :name => nil, :class => "ui button"  %>
				</div>
			<% end %>
		</div>
	<% end %>

	<div class="sixteen wide column">
		<ul class="posts-list">
			<% @posts.each do |post| %>
			<li class="ui segment">
				<div>
					<p><strong><%= link_to post.category.name.capitalize, category_path(post.category.name.downcase) %></strong> • 
					Posted by <%= link_to post.user.name.capitalize, user_path(post.user) %> 
					<%= time_ago_in_words(post.created_at) %> ago</p>
				</div>
				<h2 class="ui header"><%= link_to post.title, post_path(post) %></h2>
				<p><%= post.comments.count %> Comments</p>
			</li>
			<% end %>
		</ul>

	</div>

</div>